INSERT INTO categories (type, description)
VALUES ('Kitchen Appliences', 'Appliances of all sorts and sizes for your kitchen!'),
('Kitchen Appliences', 'Appliances of all sorts and sizes for your kitchen!'),
('Sports Wear', 'All coll!'),
('Toys and Games', 'Appliances of all sorts and sizes for your kitchen!'),
('Electronics', 'Appliances of all sorts and sizes for your kitchen!'),
('Books', 'Appliances of all sorts and sizes for your kitchen!'),
('Kids Wear', 'Appliances of all sorts and sizes for your kitchen!'),
('Mens Wear', 'Appliances of all sorts and sizes for your kitchen!'),
('Shoes', 'Appliances of all sorts and sizes for your kitchen!'),
('Womens Wear', 'Appliances of all sorts and sizes for your kitchen!'),
